In [1]:
import pandas as pd
import numpy as np

In [14]:
file_path = 'data/horarios.csv'

df = pd.read_csv(file_path, sep=';', encoding='latin')
df.columns

Index(['cnpj', 'razao_social', 'data_autorizacao', 'prefixo',
       'descricao_linha', 'tipo_veiculo', 'sentido', 'horario',
       'segunda_feira', 'terca_feira', 'quarta_feira', 'quinta_feira',
       'sexta_feira', 'sabado', 'domingo', 'janeiro', 'fevereiro', 'marco',
       'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro',
       'novembro', 'dezembro'],
      dtype='object')

In [26]:
df.head()

,cnpj,razao_social,data_autorizacao,prefixo,descricao_linha,tipo_veiculo,sentido,horario,segunda_feira,terca_feira,...,marco,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro
0,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,08/07/2016,12-0140-00,BRASILIA(DF) - CALDAS NOVAS(GO),CONVEN. C/ SANITÁRIO,ida,14:00,x,x,...,x,x,x,x,x,x,x,x,x,x
1,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,08/07/2016,12-0140-00,BRASILIA(DF) - CALDAS NOVAS(GO),CONVEN. C/ SANITÁRIO,volta,07:00,x,x,...,x,x,x,x,x,x,x,x,x,x
2,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,06/11/2018,12-0140-61,BRASILIA(DF) - CALDAS NOVAS(GO),EXECUTIVO,ida,07:30,x,x,...,x,x,x,x,x,x,x,x,x,x
3,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,06/11/2018,12-0140-61,BRASILIA(DF) - CALDAS NOVAS(GO),EXECUTIVO,volta,14:00,x,x,...,x,x,x,x,x,x,x,x,x,x
4,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,15/05/2017,12-0274-00,CALDAS NOVAS(GO) - ARAGUARI(MG),CONVEN. C/ SANITÁRIO,ida,06:45,NaN,NaN,...,x,x,x,x,x,x,x,x,x,x

In [38]:
df['time'] = pd.to_datetime(df['horario'], dayfirst=False)
df.head(3)

,cnpj,razao_social,data_autorizacao,prefixo,descricao_linha,tipo_veiculo,sentido,horario,segunda_feira,terca_feira,...,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro,time
0,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,08/07/2016,12-0140-00,BRASILIA(DF) - CALDAS NOVAS(GO),CONVEN. C/ SANITÁRIO,ida,14:00,x,x,...,x,x,x,x,x,x,x,x,x,2022-05-28 14:00:00
1,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,08/07/2016,12-0140-00,BRASILIA(DF) - CALDAS NOVAS(GO),CONVEN. C/ SANITÁRIO,volta,07:00,x,x,...,x,x,x,x,x,x,x,x,x,2022-05-28 07:00:00
2,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,06/11/2018,12-0140-61,BRASILIA(DF) - CALDAS NOVAS(GO),EXECUTIVO,ida,07:30,x,x,...,x,x,x,x,x,x,x,x,x,2022-05-28 07:30:00

In [56]:
filter1 = df['razao_social'].value_counts() == 2
filtered_list = list(filter1[filter1].index)

filtered_df = df[df['razao_social'].isin(filtered_list)]

In [62]:
series_min = pd.pivot_table(filtered_df, index='razao_social', values='time', aggfunc='min')
series_max = pd.pivot_table(filtered_df, index='razao_social', values='time', aggfunc='max')

series_max - series_min

Timestamp('2022-05-28 01:00:00')